# Form implementation generated from reading ui file 'choose_color_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChooseColorWindow(object):
    def setupUi(self, ChooseColorWindow):
        ChooseColorWindow.setObjectName("ChooseColorWindow")
        ChooseColorWindow.resize(324, 264)
        ChooseColorWindow.setStyleSheet("#centralwidget {\n"
"    background-color: rgb(141, 141, 211);\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    padding: 10px 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px  solid rgb(55, 107, 113);\n"
"    cursor: pointer;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit {\n"
"    padding: 5px;\n"
"    border-radius:5px;\n"
"    color: rgb(55, 107, 113);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=ChooseColorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_send = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        font.setBold(True)
        self.button_send.setFont(font)
        self.button_send.setObjectName("button_send")
        self.gridLayout_3.addWidget(self.button_send, 4, 0, 1, 1)
        self.choose_room_text = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.choose_room_text.setStyleSheet("QTextBrowser {\n"
"    padding-top: 5px;\n"
"}")
        self.choose_room_text.setObjectName("choose_room_text")
        self.gridLayout_3.addWidget(self.choose_room_text, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setStyleSheet("background-color: white;\n"
"border: 1px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        ChooseColorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ChooseColorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 324, 22))
        self.menubar.setObjectName("menubar")
        ChooseColorWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ChooseColorWindow)
        self.statusbar.setObjectName("statusbar")
        ChooseColorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChooseColorWindow)
        QtCore.QMetaObject.connectSlotsByName(ChooseColorWindow)

    def retranslateUi(self, ChooseColorWindow):
        _translate = QtCore.QCoreApplication.translate
        ChooseColorWindow.setWindowTitle(_translate("ChooseColorWindow", "MainWindow"))
        self.button_send.setText(_translate("ChooseColorWindow", "OK"))
        self.choose_room_text.setHtml(_translate("ChooseColorWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:700;\">CHOOSE COLOR</span></p></body></html>"))
        self.pushButton.setText(_translate("ChooseColorWindow", "CHOOSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChooseColorWindow = QtWidgets.QMainWindow()
    ui = Ui_ChooseColorWindow()
    ui.setupUi(ChooseColorWindow)
    ChooseColorWindow.show()
    sys.exit(app.exec())
